[package]
name = "lolcat"
version = "0.1.0"
authors = ["Dan White <github@bluetufa.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.11.0"
rand = "0.5.5"
